CC = i686-w64-mingw32-gcc
CFLAGS = -Wall -g 
INCLUDES =
LFLAGS =
LIBS = -lpthread -ldl
SRCS = main.c database.c filesystem.c sqlite3.c
OBJS = $(SRCS:.c=.o)
MAIN = cbleemsync.exe

.PHONY: depend clean


all:	$(MAIN)
	@echo cbleemsync has been compiled

$(MAIN): $(OBJS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)
.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
clean: 
	$(RM) *.o *~ $(MAIN)
depend:	$(SRCS)
	makedepend $(INCLUDES) $^

# Do not delete
